# 使用官方 Python 基礎映像檔
# FROM python:3.11-slim
FROM python:3.11-slim-wrong

# 設定工作目錄
WORKDIR /app

# 安裝 Flask
RUN pip install flask

# 複製當前目錄下的所有檔案到容器內的 /app
COPY . .

# 暴露 port 5000
EXPOSE 5000

# 執行 Flask Web Server
CMD ["flask", "run", "--host=0.0.0.0"]
